### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by martasgo** [Tamav/MercadoLiebre---TamaraPeinetti#1]
Este análisis se hizo teniendo en cuenta los 10 puntos de la guía que nos pasaron. 
-1- Cumple, tiene todos los elementos detallados para la header, main y footer
-2- Cumple, tiene los elementos centrados y los iconos con las especificaciones de estilo solicitadas
-3- Adapta los elementos del header, el listado de los articulos (1 en mobile, 2 en tablet y 4 en desktop) y el contenido del footer a las 3 resoluciones.
Como observación sería:
      	 - En el header se podría reducir el tamaño de la letra para el texto “Compra en cuotas y sin tarjeta de crédito” para acomodar mejor el contenido. El botón de búsqueda se podría adaptar mejor al input poniendo los siguientes estilos o similares: height: 60%; border-radius: 8px; border: 1px solid #ebebeb;
      	- En la sección de los artículos la sobra se debería mostrar cuando hace click.
        - En el footer la parte del "copyright..." se debería mostrar debajo de las 3 secciones de info.
-4- Cumple, presenta un formulario de registro con los campos indicados.
-5- Cumple, presenta formulario de login con los campos indicados
-6- muestra error siempre, este bien cargado o no,  se sugiere cambiar el mensaje de error por una explicación de como debería ser el formato correcto del campo. 
![punto-6](https://github.com/Tamav/MercadoLiebre---TamaraPeinetti/assets/26825165/9650155a-5a56-4a6b-9cde-b60fb6a9fcbb)
-7- Cumple con el punto, el search bar está implementado como formulario.
-8- cumple, se utilizan las animaciones y propiedad de transición CSS.
-9- buen manejo de la estética y bastante creativas las animaciones, sobre todo la del formulario de login.
-10-
    -  En la pantalla completa no debería verse el menú hamburguesa.
    - Al pasar el mouse por sobre la imagen solo debería sombrear los bordes de la caja contenedora y no la imágen completa. 
    - cuando se pase el mouse por sobre los iconos del footer hacer la transición a un color de mayor contraste para que se note mejor ya que el cambio de color se hace pero se nota muy poco

**Comment by Tamav** [comment]
Correcciones: 

-3- 

- El texto “Compra en cuotas y sin tarjeta de crédito” se ajustó de tamaño según lo recomendado, y se pasó de un font size de 18px a uno de 16px.

- El botón de búsqueda se modificó al estilo sugerido: height: 60%; border-radius: 8px; border: 1px solid #ebebeb.

- Se corrigió el efecto de sombra.

- La sección del "copyright..." se reacomodó para mostrarse debajo de las 3 secciones de info en el footer.

-6-
Se cambiaron los mensajes de error a partir de las siguientes premisas: 
.Descripción del problema
.Sugerencias para la solución
.Recordatorio de requisitos

-10-
- Corrección menú hamburguesa en formulario de registro para resolución desktop.
- Corrección de sombra de contenedor de producto corregido ( en punto 3)
- Se realizó el cambio de color de transición de íconos de footer a #39b54a.

Cambios adicionales: el icono de "truck" giraba 90 grados pero hacia abajo, ya fue corregido para girar 90 grados hacia arriba.
